[[form]]
key = "add-asset"
selectbox_tables = ["locations"]
selectbox_columns = ["name"]
selectbox_labels = ["Room"]
selectbox_cross_reference_tables = ["asset_registrar"]
selectbox_cross_reference_columns = ["location_id"]
text_input_columns = ["name", "serial_number", "manufacturer"]
text_input_labels = ["Machine Name", "Machine Serial Number", "Manufacturer"]
number_input_columns = [""]
number_input_labels = [""]
radio_columns = ["is_automated"]
radio_labels = ["Automated?"]
radio_options = [["Yes", "No"]]

[[form]]
key = "add-station"
selectbox_tables = ["locations", "asset_registrar"]
selectbox_columns = ["name", "manufacturer"]
selectbox_labels = ["Room", "Manufacturer"]
selectbox_cross_reference_tables = ["asset_registrar"]
selectbox_cross_reference_columns = ["location_id"]
selectbox_chosen_reference_tables = ["locations"]
selectbox_chosen_reference_columns = ["id"]
text_input_columns = ["name", "description"]
text_input_labels = ["Station Name", "Description"]
number_input_columns = [""]
number_input_labels = [""]
radio_columns = [""]
radio_labels = [""]
radio_options = []

[[form]]
key = "add-part"
selectbox_tables = ["locations", "asset_registrar", "stations", "component_type"]
selectbox_columns = ["name", "manufacturer", "name", "component_type"]
selectbox_labels = ["Room", "Manufacturer", "Station", "Component Type"]
selectbox_cross_reference_tables = ["asset_registrar", "stations"]
selectbox_cross_reference_columns = ["location_id", "asset_id"]
text_input_columns = ["name", "part_number", "manufacturer"]
text_input_labels = ["Part Name", "Part Number", "Manufacturer"]
number_input_columns = ["on_hand"]
number_input_labels = ["Quantity On Hand"]
radio_columns = [""]
radio_labels = [""]
radio_options = [[]]
